In [48]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

#Download Folder
from google.colab import files

In [2]:
#read in data using pandas
train_df = pd.read_csv('handData.csv')
#check data has been read in properly
print(train_df)

      0         1         2         3         4         5         6         7  \
0     1  0.407496  0.799822  0.456413  0.704660  0.488068  0.611773  0.498702   
1     1  0.402933  0.804354  0.449389  0.709616  0.488956  0.619628  0.504062   
2     1  0.412153  0.803865  0.461189  0.702352  0.498637  0.598315  0.512938   
3     1  0.442410  0.802408  0.476132  0.706220  0.528193  0.624632  0.564195   
4     1  0.458069  0.816466  0.490381  0.732236  0.540285  0.643369  0.562085   
...  ..       ...       ...       ...       ...       ...       ...       ...   
3995  4  0.746221  0.705949  0.729081  0.607750  0.695687  0.518780  0.648658   
3996  4  0.726092  0.656194  0.656456  0.604025  0.608877  0.532901  0.576335   
3997  4  0.754957  0.647447  0.679147  0.613617  0.617628  0.570393  0.575156   
3998  4  0.763678  0.623972  0.694183  0.593803  0.640363  0.542748  0.601921   
3999  4  0.757779  0.622182  0.675059  0.571310  0.628295  0.516105  0.593579   

             8         9  .

In [ ]:
#create a dataframe with all training data except the target column
X = train_df.drop(columns=["0"])

#check that the target variable has been removed
print(X)

In [27]:
X.shape

(4000, 42)

In [28]:
data_y = train_df["0"]
data_y[0:5]
data_y.shape

(4000,)

In [29]:
def MultiLabelMaker(y, No_labels):
    train_Y = []
    for i in y:
        labels = np.array([0]*No_labels)
        labels[i-1] = 1
        train_Y.append(labels)
    return np.array(train_Y)


In [30]:
Y = MultiLabelMaker(data_y, 4)
print(Y)
    

[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 ...
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, random_state=42)

In [16]:
#create model
model = Sequential()

#get number of columns in training data
n_cols = X.shape[1]

#add layers to model
model.add(Flatten(input_shape=(n_cols,)))
model.add(Dense(64, activation='relu' ))
model.add(Dense(128, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(4, activation='softmax'))

In [35]:
def model(X):
    #create model
    model = Sequential()

    #get number of columns in training data
    n_cols = X.shape[1]

    #add layers to model
    model.add(Flatten(input_shape=(n_cols,)))
    model.add(Dense(64, activation='relu' ))
    model.add(Dense(128, activation='relu'))
    model.add(Dense(512, activation='relu'))
    model.add(Dense(64, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(4, activation='softmax'))
    return model


In [36]:
model_2 = model(X_train)

In [37]:
#compile model using accuracy to measure model performance
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [40]:
#train model
model_2.fit(X_train, y_train, epochs=30, validation_split=0.2)

Epoch 1/30
80/80 [==============================] - 2s 10ms/step - loss: 1.1711 - accuracy: 0.4652 - val_loss: 0.9024 - val_accuracy: 0.5391
Epoch 2/30
80/80 [==============================] - 0s 4ms/step - loss: 0.8555 - accuracy: 0.6266 - val_loss: 0.7596 - val_accuracy: 0.6531
Epoch 3/30
80/80 [==============================] - 3s 39ms/step - loss: 0.6589 - accuracy: 0.7203 - val_loss: 0.5786 - val_accuracy: 0.7641
Epoch 4/30
80/80 [==============================] - 0s 4ms/step - loss: 0.5154 - accuracy: 0.7883 - val_loss: 0.5029 - val_accuracy: 0.7547
Epoch 5/30
80/80 [==============================] - 0s 5ms/step - loss: 0.4641 - accuracy: 0.8012 - val_loss: 0.4476 - val_accuracy: 0.8266
Epoch 6/30
80/80 [==============================] - 2s 22ms/step - loss: 0.3899 - accuracy: 0.8418 - val_loss: 0.3618 - val_accuracy: 0.8781
Epoch 7/30
80/80 [==============================] - 0s 5ms/step - loss: 0.3566 - accuracy: 0.8641 - val_loss: 0.3100 - val_accuracy: 0.9078
Epoch 8/30
80/80 

In [42]:
prediction = model_2.predict(X_test)

25/25 [==============================] - 1s 19ms/step


In [47]:
model_2.save("handPose")

In [49]:
!zip -r /content/handPose.zip /content/handPose
files.download("/content/handPose.zip")

  adding: content/handPose/ (stored 0%)
  adding: content/handPose/assets/ (stored 0%)
  adding: content/handPose/saved_model.pb (deflated 89%)
  adding: content/handPose/fingerprint.pb (stored 0%)
  adding: content/handPose/keras_metadata.pb (deflated 91%)
  adding: content/handPose/variables/ (stored 0%)
  adding: content/handPose/variables/variables.index (deflated 64%)
  adding: content/handPose/variables/variables.data-00000-of-00001 (deflated 20%)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>